### ISSUE TITLE
Changes to css and devices

### ISSUE THREAD

**Issue by thehands1** [open-dash/open-dash-diy#15]
How can we keep changes to css files and device templates so updates don't break or lose things.

**Comment by pstuart** [comment]
implemented templates today.  Working on similar for css.  Maybe follow this model? `{"styles" : { "global" : "<Global CSS HERE>", "dashboards" : [{"id" : "0", "css" : "<DASH CSS HERE>"}, {"id" : "1", "css" : "<DASH CSS HERE>"}] }`

**Comment by pstuart** [comment]
implemented
