### ISSUE TITLE
Typo for sqaure

### ISSUE THREAD

**Issue by thehands1** [open-dash/open-dash-diy#16]
In dashboard.js sqaure is typed wrong.  I checked all the files and it is the only place.

var showTiles = function() {
    var tiles = $(".tile, .tile-small, .tile-sqaure, .tile-wide, .tile-large, .tile-big, .tile-super");

**Comment by patrickstuart** [comment]
thanks, will be fixed in next push

**Comment by pstuart** [comment]
fixed
