### ISSUE TITLE
Current value not showing for device type

### ISSUE THREAD

**Issue by thehands1** [open-dash/open-dash-diy#18]
When you go look to see what a devices type is in the edit screen, it doesn't show the current value in the list box.  Use to have it there.

**Comment by pstuart** [comment]
yeah, this will be added at a later date, right now it only shows the original value from when it cached the devices response from ST.

**Comment by thehands1** [comment]
It doesn’t even do that for me anymore it used to.  Now if I add a new device type assign it to a device it won’t show up as the selected item after I save it.

 

Larry

**Comment by thehands1** [comment]
I also have to use an existing device type or it doesn’t work at att.  So to get around this I just modified the blank it works.  But this only solves it for 1 type.  Something broke.

 

Larry

**Comment by pstuart** [comment]
ok I think I fixed it.
